spring:
  application:
    name: loan-gateway

  # Настройки подключения к PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/loan_db
    username: loan_admin
    password: loan_super_secret_password
    driver-class-name: org.postgresql.Driver
    # Настройки пула соединений HikariCP
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # Настройки JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Настройки подключения к Apache Kafka
  kafka:
    bootstrap-servers: localhost:9092

    # 1. Настройки ОТПРАВИТЕЛЯ
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # 2. Настройки СЛУШАТЕЛЯ
    consumer:
      group-id: gateway-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.microloan.gateway.dto.ScoringResult

# Настройки сетевого уровня
server:
  port: 8081

# Настройки Actuator и Micrometer для сбора метрик прометеуса и графаны
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name} # Сквозной тег для Grafana, чтобы группировать метрики по имени сервиса