server:
  port: 8082

spring:
  application:
    name: scoring-service

  kafka:
    bootstrap-servers: localhost:9092

    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: "*"
      spring.json.use.type.headers: false
      spring.json.value.default.type: com.microloan.scoringservice.dto.LoanApplicationEvent

    consumer:
      group-id: scoring-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer